/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        accent: "var(--accent)",
        cream: "var(--cream)",
        warm: "var(--warm)",
        sage: "var(--sage)",
        brown: "var(--brown)",
        sand: "var(--sand)",
        stone: "var(--stone)",
        gold: "var(--gold)",
        success: "var(--success)",
        sale: "var(--sale)",
        line: "var(--border)",
        ivory: "#F7F9FC",
        porcelain: "#EDF2F7",
        beige: "#D1DAE3",
        taupe: "#B8C5D1",
        charcoal: "#0A1F33",
        bronze: "#1A2332",
        muted: "#7A8FA3",
        oldcream: "#FFF7EE",
        oldbeige: "#E8D8C9",
        oldbrown: "#7E6456",
        oldnavy: "#0C2D48",
        oldblue: "#2E86AB",
        oldlightblue: "#8CBED6",
        oldsand: "#D1DAE3",
        oldlightcream: "#F2EADB",
      },
      fontFamily: {
        cairo: ["var(--font-heading)", "sans-serif"],
        roboto: ["var(--font-body)", "sans-serif"],
        inter: ["Roboto", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
    },
  },
  plugins: [],
};
