/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        accent: "var(--accent)",
        cream: "var(--cream)",
        warm: "var(--warm)",
        sage: "var(--sage)",
        brown: "var(--brown)",
        sand: "var(--sand)",
        stone: "var(--stone)",
        gold: "var(--gold)",
        success: "var(--success)",
        sale: "var(--sale)",
        line: "var(--border)",
        ivory: "#FEFEFE",
        porcelain: "#F3F0EB",
        beige: "#D9CEC4",
        taupe: "#C8BCB1",
        charcoal: "#1F1C15",
        bronze: "#463623",
        muted: "#8E806F",
        oldcream: "#FFF7EE",
        oldbeige: "#E8D8C9",
        oldbrown: "#7E6456",
        oldnavy: "#20323E",
        oldblue: "#6A93A8",
        oldlightblue: "#B0C8D6",
        oldsand: "#CDBCA6",
        oldlightcream: "#F2EADB",
      },
      fontFamily: {
        cairo: ["var(--font-heading)", "sans-serif"],
        roboto: ["var(--font-body)", "sans-serif"],
        amiri: ["var(--font-logo-ar)", "serif"],
        poppins: ["Poppins", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
